### ISSUE TITLE
KeyError: 'metrics'

### ISSUE THREAD

**Issue by chainfitness** [LitingLin/SwinTrack#13]
when I run main.py in order to test got10k(test) only, KeyError: 'metrics' is found. what should I do? the fully log as follow:

**ssh://rzh@192.168.0.213:22/home/rzh/anaconda3/bin/python3 -u /home/rzh/win-pycharm/SwinTrack/main.py SwinTrack Tiny --mixin_config got10k.yaml**
Not using distributed mode
Traceback (most recent call last):
  File "/home/rzh/win-pycharm/SwinTrack/main.py", line 6, in <module>
    main(os.path.dirname(__file__))
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/main.py", line 104, in main
    entry(args)
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/entry.py", line 25, in entry
    load_static_mixin_config_and_apply_rules(runtime_vars, config)
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/mixin_utils.py", line 87, in load_static_mixin_config_and_apply_rules
    apply_mixin_rules(mixin_config['mixin'], config, None)
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/mixin_utils.py", line 64, in apply_mixin_rules
    _apply_mixin_rule(fixed_modification_rule, config, None)
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/mixin_utils.py", line 24, in _apply_mixin_rule
    mod_config(config, query_path, value)
  File "/home/rzh/win-pycharm/SwinTrack/core/entry/dict_flatten_accessor.py", line 24, in mod_config
    config = config[sub_path] if not sub_path.isdigit() else config[int(sub_path)]
KeyError: 'metrics'

**Comment by LitingLin** [comment]
Have you tried the lastest version from GitHub? It should be no problem now.

**Comment by chainfitness** [comment]
I tried the latest version just now, and it looks like the full data of got10k is essential to execute the main.py. I just want to test got10k(test) only due to the factor that the full data is too giant to download quickly in china. Could you help me by telling me about the step to test got10k only?
![image](https://user-images.githubusercontent.com/70508044/146107775-ff18ecd3-79a4-458b-b675-a64f5d0082f1.png)

**Comment by chainfitness** [comment]
Could you tell me the got10k tracking result you uploaded in the repo is based on which hardware platform?

**Comment by LitingLin** [comment]
Download the metadata cache and put in the right space, then you don't need to construct from the raw dataset.
Download the val split and test split of the GOT-10k, put them into the ```val``` and ```test``` folder. That is enough for GOT-10k only evaluation.

V100 GPU

**Comment by LitingLin** [comment]
Applying multiple config modification patch is allowed. So you can evaluate the model like ```python main.py SwinTrack Tiny --weight_path /path/to/weight.pth --mixin_config evaluation.yaml --mixin_config got10k.yaml```

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chainfitness ***@***.***>
发送时间: Wednesday, December 15, 2021 10:23:17 AM
收件人: LitingLin/SwinTrack ***@***.***>
抄送: LitingLin ***@***.***>; Comment ***@***.***>
主题: Re: [LitingLin/SwinTrack] KeyError: 'metrics' (Issue #13)


Could you tell me the got10k tracking result you uploaded in the repo is based on which hardware platform?

―

**Comment by chainfitness** [comment]
> 

The step followed as you indicate was conducted, it works. thx for your reply so quickly, and expecting the release of the inference code.
