### ISSUE TITLE
how to apply Swingtrack to execute a video demo like TransT or pysot .etc?

### ISSUE THREAD

**Issue by chainfitness** [LitingLin/SwinTrack#14]
I want to test this awesome job to compare with pysot and TransT employed to the actual project. Could you mind telling me how to utilize this job to execute a video demo?

**Comment by LitingLin** [comment]
The inference code path will be released later. But not now. Sorry for inconvenience.

**Comment by chainfitness** [comment]
thx for your patience, and expecting your update!

**Comment by artemkurylev** [comment]
> The inference code path will be released later. But not now. Sorry for inconvenience.

Hi, do you have any plans on it?

**Comment by shen338** [comment]
Hello, do you guys have an ETA on a demo file?
