### ISSUE TITLE
error of evaluation

### ISSUE THREAD

**Issue by maoyw57** [LitingLin/SwinTrack#15]
When I evaluate your model in got10k, I find this error in windows. Could you tell me the reason?
![image](https://user-images.githubusercontent.com/73291365/145999362-d39809b4-7c15-40d2-aba0-c63c24ba7ec7.png)

**Comment by LitingLin** [comment]
Looks like you are evaluating on the train split of GOT-10k, that is not reasonable.

The direct cause in the screenshot is that the first frame of the sequence has no bounding box annotation.

**Comment by JackjackFan** [comment]
> When I evaluate your model in got10k, I find this error in windows. Could you tell me the reason? ![image](https://user-images.githubusercontent.com/73291365/145999362-d39809b4-7c15-40d2-aba0-c63c24ba7ec7.png)

Hey,Sir,I evaluate author's model in got10k, I find this error in windows. Have you meet this error before?How did you solve it?Could you give me hand?Thank you very much!

File "/home/cv/code/SwinTrack/datasets/SOT/seed/Impl/GOT10k.py" line 539,in _construct_GOT10k_non_public_data
assert bounding_box.ndim ==1 and bounding_box.shape[0]=4
AssertionError
