### ISSUE TITLE
issues about the Weak aug(Positional Augmentations) in swintrack

### ISSUE THREAD

**Issue by JackjackFan** [LitingLin/SwinTrack#17]
hello,Congradulations,nice work.I have some questions about your positional augmentations in paper.What the weak aug means in swintrack?Does it means you did not apply any pre-process deducing random scale and random translation during the search image generation in the training phase?If so, what did you do during the preprocessing stage? 
At last,,,,this work makes me feel frustrated,cause I have been tried this method for about 5 months,but I did not make the trackers outperform yours hhh.

**Comment by LitingLin** [comment]
Thanks.

Here is the [weak aug. conf](https://github.com/LitingLin/SwinTrack/blob/main/config/SwinTrack/Tiny/mixin/weak_aug.yaml), smaller scale and translation jitter in this config. It just show that SwinTrack is also sensitive to the center bias, which is described in SiamRPN++, and a proper position jitter is essential.

**Comment by JackjackFan** [comment]
非常感谢~
