### ISSUE TITLE
Hello!About the track speed evaluation

### ISSUE THREAD

**Issue by davidyang180** [LitingLin/SwinTrack#18]
Hello!During the test, I set time stamps before and after tracking a single frame by referring to the time module, but it is not as fast as described in the paper. Isn't the evaluation of tracking time calculated in this way?

**Comment by LitingLin** [comment]
Run 100 times and take the average.

https://github.com/LitingLin/SwinTrack/blob/4b88bcff6f09d31bc0929a7b3d8dbad4ef8a6e44/core/run/profiler/efficiency_assessor.py#L85
