### ISSUE TITLE
How can I get the train_set.txt and test_set.txt of lasot?

### ISSUE THREAD

**Issue by FreezerBreath** [LitingLin/SwinTrack#19]
I don't find the files in the link of your provided.

**Comment by HengFan2010** [comment]
It is provided here (https://drive.google.com/drive/folders/1IYnzEYbSNdj__Tx0nIX-epkJ4PBUtHB4). When you prepare the dataset, you should put them under the (LaSOT) dataset dir.

Thanks.

**Comment by FreezerBreath** [comment]
Thank you very much!

**Comment by HengFan2010** [comment]
No prob.

Jingchao Wang ***@***.***>于2021年12月28日 周二下午7:26写道：
