### ISSUE TITLE
training time and batchsize

### ISSUE THREAD

**Issue by ANdong-star** [LitingLin/SwinTrack#2]
Hi, thanks for your work!  How long does the swintrack training take, and how much do you set the batchsize to?

**Comment by LitingLin** [comment]
Thanks for the issue.

| Config | Batch size | Training Time |
| --------- | ----------- | --------- |
| SwinTrack-Tiny | 128 on Single GPU | ~20 hours on 8 V100 |
| SwinTrack-Base | 64 on Single GPU | ~2 days on 8 V100 |
| SwinTrack-Base-384 | 64 on Single GPU | ~4 days on 8 V100 |
