### ISSUE TITLE
i find this problem

### ISSUE THREAD

**Issue by little-siskin** [LitingLin/SwinTrack#28]
when i use `~/SwinTrack$ python main.py SwinTrack Tiny --output_dir /home/zhangruilin/SwinTrack/output --mixin_config got10k.yaml`

it returns me
`Traceback (most recent call last):
  File "main.py", line 6, in <module>
    main(os.path.dirname(__file__))
  File "/home/zhangruilin/SwinTrack/core/entry/main.py", line 110, in main
    entry(args)
  File "/home/zhangruilin/SwinTrack/core/entry/entry.py", line 73, in entry
    build_and_run(runtime_vars, config, wandb_instance)
  File "/home/zhangruilin/SwinTrack/core/entry/build_and_run.py", line 21, in build_and_run
    run = build(runtime_vars, network_config, global_synchronized_rng, local_rng, wandb_instance)
  File "/home/zhangruilin/SwinTrack/core/run/builder.py", line 312, in build
    model, pseudo_data_generator, running_tasks, global_event_dispatcher, default_logger, num_epochs = build_running_tasks(runtime_vars, config, global_rng, local_rng, wandb_instance)
  File "/home/zhangruilin/SwinTrack/core/run/builder.py", line 262, in build_running_tasks
    _build_data_loaders(runtime_vars, branch_config, data_config, config, global_rng, local_rng, building_context)
  File "/home/zhangruilin/SwinTrack/core/run/builder.py", line 182, in _build_data_loaders
    data_context.event_register, data_context.context, is_training)
  File "/home/zhangruilin/SwinTrack/data/tracking/builder.py", line 8, in build_data_source
    data_pipelines = build_siamfc_data_source(data_config, runtime_vars, config, global_synchronized_rng, local_rng, event_register, context)
  File "/home/zhangruilin/SwinTrack/data/tracking/methods/SiamFC/builders/source.py", line 18, in build_siamfc_data_source
    runtime_vars.rank)
  File "/home/zhangruilin/SwinTrack/data/tracking/methods/SiamFC/builders/components/dataset.py", line 16, in build_siamfc_dataset
    datasets, dataset_parameters = build_datasets(dataset_config)
  File "/home/zhangruilin/SwinTrack/data/tracking/methods/_common/builders/build_datasets.py", line 23, in build_datasets
    datasets, dataset_parameters = build_dataset_from_config_distributed_awareness(dataset_config, _customized_dataset_parameter_handler)
  File "/home/zhangruilin/SwinTrack/data/utils/dataset.py", line 8, in build_dataset_from_config_distributed_awareness
    return build_datasets_from_config(config, user_defined_parameters_handler)
  File "/home/zhangruilin/SwinTrack/datasets/easy_builder/builder.py", line 148, in build_datasets_from_config
    return build_datasets(config, unknown_parameter_handler)
  File "/home/zhangruilin/SwinTrack/datasets/easy_builder/builder.py", line 120, in build_datasets
    seed = seed_class(root_path=path)
  File "/home/zhangruilin/SwinTrack/datasets/SOT/seed/LaSOT.py", line 9, in __init__
    super(LaSOT_Seed, self).__init__('LaSOT', root_path, data_split, 2)
  File "/home/zhangruilin/SwinTrack/datasets/base/factory_seed.py", line 11, in __init__
    assert root_path is not None and len(root_path) > 0
AssertionError`
i am glade to receive any advices

**Comment by little-siskin** [comment]
and i want to train on got10k  ,so i did not download LaSOT

**Comment by little-siskin** [comment]
how to train only with got10k

**Comment by little-siskin** [comment]
when i run `python main.py SwinTrack Tiny --mixin_config got10k.yaml`  it returns me the result
it seems like that the code still train with lasot

**Comment by little-siskin** [comment]
@LitingLin

**Comment by longcoolman** [comment]
are you solve this problem

**Comment by longcoolman** [comment]
could you teach me how to do that, thank you very much!
it is appreciated that you can email to me!
email address : lfm_sunny@163.com

**Comment by little-siskin** [comment]
> could you teach me how to do that, thank you very much! it is appreciated that you can email to me! email address : [lfm_sunny@163.com](mailto:lfm_sunny@163.com)

可能是需要同时存在lasot 数据集和got-10k数据集，我把两个数据集下好之后就解决这个问题了，但是在envolate阶段还是会出现这个问题

**Comment by little-siskin** [comment]
你解决这个问题了吗 ，我现在想进行test阶段又出现了这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 晚上7:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [LitingLin/SwinTrack] i find this problem (Issue #28)





 
could you teach me how to do that, thank you very much!
 it is appreciated that you can email to me!
 email address : ***@***.***

**Comment by longcoolman** [comment]
好的 谢谢 最近没管swintrack
















在 2022-03-30 14:40:54，"zhangruilin" ***@***.***> 写道：

could you teach me how to do that, thank you very much! it is appreciated that you can email to me! email address : ***@***.***

可能是需要同时存在lasot 数据集和got-10k数据集，我把两个数据集下好之后就解决这个问题了，但是在envolate阶段还是会出现这个问题

**Comment by Torch-HXM** [comment]
If you want to evaluate on got-10k only,you can change SwinTrack/datasets/easy_builder/builder.py like this:
ORIGIN:
`def build_datasets_from_config(config: dict, unknown_parameter_handler=_default_unknown_parameter_handler):
    with open(os.path.join(os.path.dirname(__file__), 'defaults.yaml'), 'rb') as fid:
        default = yaml.safe_load(fid)
    default = default['datasets']
    dataset_config = merge_config(default, config['datasets'])
    config['datasets'] = dataset_config
    return build_datasets(config, unknown_parameter_handler)`
CHANGE:
`def build_datasets_from_config(config: dict, unknown_parameter_handler=_default_unknown_parameter_handler):
    with open(os.path.join(os.path.dirname(__file__), 'defaults.yaml'), 'rb') as fid:
        default = yaml.safe_load(fid)
    default = default['datasets']
    dataset_config = merge_config(default, config['datasets'])
    #config['datasets'] = dataset_config    #修改
    config['datasets'] = {'GOT10k': {'type': 'SOT', 'splits': ['val', 'test']}}
    print('>>>config datasets:',config['datasets'])
    return build_datasets(config, unknown_parameter_handler)
`
Then you can evaluate only on got-10k.
Don't forget to add the absolute path of got-10k to SwinTrack/path.yaml
