### ISSUE TITLE
Is there any difference with STARK on the concatenation and encoder-decoder strucutre?

### ISSUE THREAD

**Issue by zugofn** [LitingLin/SwinTrack#3]
Is there any difference with STARK on the concatenation and encoder-decoder strucutre?

**Comment by HengFan2010** [comment]
> Is there any difference with STARK on the concatenation and encoder-decoder structure?

Thanks for the question.

Yes. The differences are two-fold. First, the positional encoding is different. We adopted the improved united positional encoding with adaption to tracking in the encoder which is different from STARK. We empirically found that the encoding method could bring benefits on improvement. Second, the decoder in STARK was directly borrowed from DETR, which we found may result in slow training and low accuracy. To adapt to the concatenation style feature fusion, we designed the concatenation also in the decoder. You can check our two implementations: link 1: https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/concatenated_fusion.py and link 2: https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/target_query_decoder.py. We finally used our design as in link 1, and link 2 was based on DETR which was similar to the decoder in STARK. You can refer to these two implementations.

Hope it helps.

**Comment by zugofn** [comment]
> > STARK 在串联和编码器-解码器结构上有什么不同吗？
> 
> 谢谢你的提问。
> 
> 是的。差异有两个方面。首先，位置编码不同。我们在编码器中采用了与STARK不同的改进的联合位置编码，适应跟踪。我们凭经验发现编码方法可以带来改进的好处。其次，STARK 中的解码器直接从 DETR 借用，我们发现这可能导致训练缓慢和准确率低。为了适应串联风格的特征融合，我们也在解码器中设计了串联。您可以查看我们的两个实现：链接 1：[https](https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/concatenated_fusion.py) : [//github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/concatenated_fusion.py](https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/concatenated_fusion.py)和链接 2：[https](https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/target_query_decoder.py) : [//github.com /LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/target_query_decoder.py](https://github.com/LitingLin/SwinTrack/blob/main/models/methods/SwinTrack/modules/decoder/target_query_decoder.py). 我们最终使用了链接 1 中的设计，链接 2 基于 DETR，类似于 STARK 中的解码器。你可以参考这两个实现。
> 
> 希望能帮助到你。

Thanks for your reply！
