### ISSUE TITLE
test on GOT-10k cannot finish

### ISSUE THREAD

**Issue by blxie** [LitingLin/SwinTrack#37]

**Comment by shuida** [comment]
你好，我也遇到类似的问题，请问解决了吗？

**Comment by blxie** [comment]
可以试着将 config/SwinTrack/Tiny/mixin/runs.yaml 中有关 test 部分的设置，batch_size 调低一点，我设置为 1 后就没有问题了，但是目前我改为原来的 8 后还是可以运行，我也不是特别清楚为什么会这样，但是猜测和网络也有一些关系。

**Comment by shuida** [comment]
你好，请问可以加好友私聊讨论嘛？发自我的手机-------- 原始邮件 --------发件人： Birny Tse ***@***.***>日期： 2022年5月15日周日 09:41收件人： LitingLin/SwinTrack ***@***.***>抄送： shuida ***@***.***>, Comment ***@***.***>主    题： Re: [LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37)

可以试着将 config/SwinTrack/Tiny/mixin/runs.yaml 中有关 test 部分的设置，batch_size 调低一点，我设置为 1 后就没有问题了，但是目前我改为原来的 8 后还是可以运行，我也不是特别清楚为什么会这样，但是猜测和网络也有一些关系。

**Comment by shuida** [comment]
你好，请问可以加微信私聊讨论嘛？发自我的手机-------- 原始邮件 --------发件人： ***@***.***日期： 2022年5月18日周三 15:49收件人： LitingLin/SwinTrack ***@***.***>主    题： 回复：[LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37)你好，请问可以加好友私聊讨论嘛？发自我的手机-------- 原始邮件 --------发件人： Birny Tse ***@***.***>日期： 2022年5月15日周日 09:41收件人： LitingLin/SwinTrack ***@***.***>抄送： shuida ***@***.***>, Comment ***@***.***>主    题： Re: [LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37)

可以试着将 config/SwinTrack/Tiny/mixin/runs.yaml 中有关 test 部分的设置，batch_size 调低一点，我设置为 1 后就没有问题了，但是目前我改为原来的 8 后还是可以运行，我也不是特别清楚为什么会这样，但是猜测和网络也有一些关系。

**Comment by blxie** [comment]
可以的，微信xbl2312502285



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 15:50 PM
To: ***@***.***&gt;;
Cc: "Birny ***@***.******@***.***&gt;;
Subject: Re: [LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37)




 你好，请问可以加微信私聊讨论嘛？发自我的手机-------- 原始邮件 --------发件人： ***@***.***日期： 2022年5月18日周三 15:49收件人： LitingLin/SwinTrack ***@***.***&gt;主    题： 回复：[LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37)你好，请问可以加好友私聊讨论嘛？发自我的手机-------- 原始邮件 --------发件人： Birny Tse ***@***.***&gt;日期： 2022年5月15日周日 09:41收件人： LitingLin/SwinTrack ***@***.***&gt;抄送： shuida ***@***.***&gt;, Comment ***@***.***&gt;主    题： Re: [LitingLin/SwinTrack] test on GOT-10k cannot finish (Issue #37) 
 可以试着将 config/SwinTrack/Tiny/mixin/runs.yaml 中有关 test 部分的设置，batch_size 调低一点，我设置为 1 后就没有问题了，但是目前我改为原来的 8 后还是可以运行，我也不是特别清楚为什么会这样，但是猜测和网络也有一些关系。
