### ISSUE TITLE
 assert root_path is not None and len(root_path) > 0

### ISSUE THREAD

**Issue by mywebinfo65536** [LitingLin/SwinTrack#40]
When go to train， it raised this error:
![image](https://user-images.githubusercontent.com/105631236/173825850-1a1df542-d3a4-4b0a-a77c-bd5c5ac37c26.png)

**Comment by mywebinfo65536** [comment]
-

**Comment by userlooser1** [comment]
> When go to train， it raised this error: ![image](https://user-images.githubusercontent.com/105631236/173825850-1a1df542-d3a4-4b0a-a77c-bd5c5ac37c26.png)

How did you fixed this problem?
