### ISSUE TITLE
How to evaluate existing model which used the Resnet-50 backbone?

### ISSUE THREAD

**Issue by Duranin** [LitingLin/SwinTrack#46]
作者您好，我训练了采用resnet作为backbone的对照实验，您的请问下如何进行测试呢？您的readme中的指令不适用于该情况。非常感谢您的付出。

**Comment by Duranin** [comment]
> 作者您好，我训练了采用resnet作为backbone的对照实验，您的请问下如何进行测试呢？您的readme中的指令不适用于该情况。非常感谢您的付出。

**Comment by yugezailushang** [comment]
您好，请问你是如何更换主干网络的呢
