### ISSUE TITLE
Unable to reproduce the values on LaSOT when using the provided raw results

### ISSUE THREAD

**Issue by 2006pmach** [LitingLin/SwinTrack#7]
Hi guys

Thanks for the nice work. The numerical results look great. I wanted to compare your method with recent trackers in the same success plot. Unfortunately such a comparison is missing in the paper. Hence, I tried to do this myself
but I can't reproduce your numbers whereas I get the correct numbers for KeepTrack and STARK. Maybe I am doing something wrong since your output bounding box format is different from the ones I have for KeepTrack and STARK. 

I saw that you guys use a `xyxy` format and seem to have a `-0.5` offset (not sure why though) whereas the other two use a `xywh` format. In order to convert the `xyxy` to `xywh` I used `w = x2-x1+1` and `h=y2-y1+1` and added `+0.5` for `x` and `y`. It seems that the first boxes corresponding to the initial box agree between all trackers using this conversion.

![success_plot](https://user-images.githubusercontent.com/17532717/144892101-1dd885d3-4308-4988-bfb5-0d4bf321e9b1.png)
 
I created the success plots using [pytracking](https://github.com/visionml/pytracking) and downloaded the results for STARK and KeepTrack from the corresponding repos. Maybe I am doing something that you guys were not intending.
But I get **66.7** instead of **68.1** for SwinTrack-T (**-1.4**), **69.6** instead of **71.1** for SwinTrack-B (**-1.5**) and **70.2** instead of **71.7** (**-1.5**) for SwinTrack-B-384. Would be great if you could create a similar plot that compares your trackers with the two in the same success plot and share this plot? And let me know what you did differently?
Can you maybe use in addition the [pytracking](https://github.com/visionml/pytracking) or [pysot-toolkit](https://github.com/StrangerZhang/pysot-toolkit) to evaluate your tracker just to make sure that there is no bug in your evaluation scripts. That would be awesome.

Thanks a lot and best,
Christoph

**Comment by LitingLin** [comment]
I was using the codes from GOT10k evaluation toolkit to evaluate the model on LaSOT dataset and so caused the differences. I will update the results to meet with pytracking toolkit. Many thanks to point out this.

Sorry for the inconvenience.

The main problem addressed in [calculate_metrics.py](https://github.com/LitingLin/SwinTrack/blob/1c1eb6352834f8904fd640bd1583cf099035ff53/data/tracking/methods/sequential/metric_collector/utils/calculate_metrics.py#L58).
