### ISSUE TITLE
How to change the image size of the template branch and search branch in Swin_backbone

### ISSUE THREAD

**Issue by hongsheng-Z** [LitingLin/SwinTrack#8]
Hi, thanks for your great work. At what stage of Swin did you scale the size of the images. I noticed that the original Swin has undergone a size scaling at each stage. I don’t know if you have also adopted this approach.

**Comment by LitingLin** [comment]
Yes. It is a crucial architecture design of the Swin-Transformer, and we have no reason to change it.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: hsz ***@***.***>
发送时间: Thursday, December 9, 2021 11:15:50 AM
收件人: LitingLin/SwinTrack ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LitingLin/SwinTrack] How to change the image size of the template branch and search branch in Swin_backbone (Issue #8)


Hi, thanks for your great work. At what stage of Swin did you scale the size of the images. I noticed that the original Swin has undergone a size scaling at each stage. I don’t know if you have also adopted this approach.

―

**Comment by hongsheng-Z** [comment]
Ok, Thanks for your reply, and did you perform a  'padding mask’ operation in the backbone stage like SATRK?

**Comment by LitingLin** [comment]
No

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: hsz ***@***.***>
发送时间: Thursday, December 9, 2021 5:19:05 PM
收件人: LitingLin/SwinTrack ***@***.***>
抄送: LitingLin ***@***.***>; Comment ***@***.***>
主题: Re: [LitingLin/SwinTrack] How to change the image size of the template branch and search branch in Swin_backbone (Issue #8)


Ok, Thanks for your reply, and did you perform a 'padding mask’ operation in the backbone stage like SATRK?

―
