### ISSUE TITLE
how to use this code without wandb in offline

### ISSUE THREAD

**Issue by Olrun** [LitingLin/SwinTrack#9]
hello.
first,thank you for your best work. I'm studying object tracking with your SwinTrack. but because of some situation, I don't use this in online. so how to learn and training your project in offline?(do I just add --wandb_offline in python main.py SwinTrack Tiny?)
thank, you.

**Comment by LitingLin** [comment]
We do have an option for this situation. You can even upload later by typing ```wandb sync```.

https://github.com/LitingLin/SwinTrack/blob/e209946173d1be68efbd87f3a3ce4d8585321933/core/entry/train_args.py#L23
